# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://alexyucra.github.io/blog
date_format: "ordinal"
title: Blog
subtitle: "Análise, Tecnología e Desenvolvimento"
description: "Assuntos: Análise, tecnología e Desenvolvimento"
keywords: Análise, tecnología e Desenvolvimento, alexyucra, analise, php, python, elixir, flet, ayti
timezone: America/Sao_Paulo
encoding: "utf-8"
# Ano exibido no canto inferior esquerdo da página
since: 2015
# Repositório de código-fonte, substitua-o pelo seu próprio
repository: alexyucra/blog.git
# Configuração de aceleração de CDN para recursos css e js
cdn:
    jsdelivr:
        enabled: false
# Configuração de componente opcional
components:
    # compartilhar
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # Não faça estatísticas de visitas de alhozi
    busuanzi:
        enabled: false
        start_date: 2020-05-03
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # Contagem de palavras do artigo
    word_count:
        enabled: true
    # O canto superior direito da página e o código QR na página "Sobre"
    # Por favor, substitua a imagem assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: Análise, Tecnologia e Desenvolvimento
    # Qual visualização é usada para a página de índice do wiki, lista de suporte (lista)/categoria (cate)
    wiki:
        view: cate
# Compactar o conteúdo da página
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# Lista de temhas suportados https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Alex Yucra
organization: Latin Dev
organization_url: 
github_username: alexyucra
location: Sao Paulo, Brasil
email: xalextrack@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categorias

#   -
#     href: /archives/
#     label: Arquivos

#   -
#     href: /open-source/
#     label: Código fonte

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: Quem sou

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!Importante!!! Por favor modifique as seguintes informações para sua própria aplicação
# !!!Important!!! Please modify infos below to yours
# disqus referencia：https://disqus.com
disqus:
    username: latin_dev
# gitment referencia：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# gitalk referencia：https://github.com/gitalk/gitalk#install
gitalk:
    owner: mzlogin
    repo: blog-comments
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# utterances referencia：https://utteranc.es/
utterances:
    repo: mzlogin/blog-comments
# beaudar referencia：https://beaudar.lipk.org/
beaudar:
    repo: mzlogin/blog-comments
# giscus referencia：https://giscus.app/zh-CN
giscus:
    repo: mzlogin/blog-comments
    repo-id: MDEwOlJlcG9zaXRvcnk5MzEyNzkxNw==
    category: Announcements
    category-id: DIC_kwDOBY0E7c4CRtg9
# Clique para mostrar ao usar outros componentes de comentários Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # Se deve dar suporte à pesquisa de texto completo
    fulltext: false
    # Número máximo de resultados de pesquisa a serem exibidos
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        sidebar-detail: true 
        content_header: false
        content_footer: false
